[package]
name = "market_forge"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-ringbuf = "0.3.6"
env_logger = "0.11.10"
fake = {version="4.3.0", features=["derive"]}
log = {version="0.4.30", features=["release_max_level_info"]}
rand = "0.10.1"
rkyv = "0.8.16"
rustc-hash = "2.1.2"
slab = "0.4.9"
smallvec = "1.15.1"
tabled = "0.19.0"
thiserror = "2.0.18"
tokio = { version = "1", features = ["full"] }

[profile.release]
debug = false
opt-level = 3
lto = true
strip = true

[profile.bench]
# inherits = "release"
debug = 1
lto = false
strip = false

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
stats_alloc = "0.1.10"

[[bench]]
name = "perf_order"
path = "benches/perf_order.rs"
harness = false

[[bench]]
name = "perf_rkyv"
path = "benches/perf_rkyv.rs"
harness = false

[[bench]]
name = "perf_socket"
path = "benches/perf_socket.rs"
harness = false

[[bench]]
name = "perf_pool"
path = "benches/perf_pool.rs"
harness = false
