[package]
name = "market_forge"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
env_logger = "0.11.10"
fake = {version="4.3.0", features=["derive"]}
log = "0.4.30"
rand = "0.10.2"
rkyv = "0.8.16"
slab = "0.4.9"
tabled = "0.19.0"
thiserror = "2.0.18"
tokio = { version = "1", features = ["full"] }
v = "0.1.0"

[profile.release]
debug = false
opt-level = 3
lto = true
strip = true

[profile.bench]
inherits = "release"
# debug = 1
# lto = false
# strip = false

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "perf_order"
path = "benches/perf_order.rs"
harness = false
